config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def show
  end
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def edit
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    @article.destroy
    redirect_to articles_path
  end
  
  private
  
  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end
  
  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  
  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category was successfully updated"
      redirect_to @category
    else
      render 'edit'
    end
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:danger] = "Only admins can perform that aciton"
      redirect_to categories_path
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  
  def  about
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something worng with your login detail"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out"
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def edit
  end
  
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end
  
  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:success] = "Account and all associated articles were successfully deleted"
    redirect_to root_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto d-block")
  end
  
end

app/views/articles/_articles.html.erb
<div class="row gx-4 gx-lg-5 d-flex justify-content-center">
  <div class="col-lg-8">
    <% @articles.each do |article| %>
      <div class="card text-center mt-4">
        <div class="card-header">
          by <%= link_to article.user.username, user_path(article.user_id) %>
          <% if article.categories.any? %>
            <div class="mt-2"><%= render article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= article.title %></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to 'Show', article_path(article.id), class: "btn btn-outline-info" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to 'Edit', edit_article_path(article.id), class: "btn btn-outline-primary" %>
              <%= link_to 'Delete', article_path(article.id), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
            <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago
          </small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<%= form_with(model: @article, local: true) do |f| %>

  <div class="row align-items-center pt-4 pb-3">
    <div class="col-md-3 ps-5">
      <%= f.label :title, class: "form-label mb-0" %>
    </div>
    <div class="col-md-9 pe-5">
      <%= f.text_field :title, class: "form-control", placeholder: "Title of article" %>
    </div>
  </div>
  
  <div class="row pt-4 pb-3">
    <div class="col-md-3 ps-5">
      <%= f.label :description, class: "form-label mb-0" %>
    </div>
    <div class="col-md-9 pe-5">
      <%= f.text_area :description, class: "form-control", rows: 10, placeholder: "Description of article" %>
    </div>
  </div>
  
  <div class="row pt-4 pb-3">
    <div class="col-md-3 ps-5">
      <%= f.label :category, class: "form-label mb-0" %>
    </div>
    <div class="col-md-9 pe-5">
      <%= f.collection_select(:category_ids, Category.order(:name), :id, :name, 
      { prompt: 'Make your selection from the list below (can be empty)' }, { multiple: true, size: 3, class: "form-select" }) %>
    </div>
  </div>
  
  <div class="d-flex">
    <%= f.submit class: "btn btn-outline-primary mx-auto" %>
  </div>
  
<% end %>

app/views/articles/edit.html.erb
<main class="vh-100">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-xl-9">
        <div class="card text-black rounded">
          <div class="card-body p-5">
            <h1 class="text-center fw-bold mb-4 mx-1 mx-md-4 mt-4">Edit article</h1>
            <%= render 'form' %>
            <div class="row justify-content-center mt-3">
              <%= link_to "Cancel and return to article", article_path(@article), class: "link-dark text-center" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/articles/index.html.erb
<main>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 d-flex justify-content-center">
      <h1 class="col-lg-8 text-center text-white">Listing Articles</h1>
    </div>
    <div class="flickr_pagination">
      <%= will_paginate @articles, :container => false %>
    </div>
    <%= render 'articles' %>
    <div class="flickr_pagination my-4">
      <%= will_paginate @articles, :container => false %>
    </div>
  </div>
</main>

app/views/articles/new.html.erb
<main class="vh-100">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-xl-9">
        <div class="card text-black rounded">
          <div class="card-body p-5">
            <h1 class="text-center fw-bold mb-4 mx-1 mx-md-4 mt-4">Creating a new article</h1>
            <%= render 'form' %>
            <div class="row justify-content-center mt-3">
              <%= link_to "Cancel and return to articles listing", articles_path, class: "link-dark text-center" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/articles/show.html.erb
<main>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 d-flex justify-content-center">
      <h2 class="col-lg-8 text-center text-white"><%= @article.title %></h2>
    </div>
    <div class="row gx-4 gx-lg-5 d-flex justify-content-center">
      <div class="col-lg-8">
        <div class="card mt-4">
          <div class="card-header text-center">
            by <%= @article.user.username %>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            <% if @article.categories.any? %>
              <div class="mt-2"><%= render @article.categories %></div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text"><%= simple_format(@article.description) %></div>
            <div class="text-center">
              <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-primary" %>
                <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
              <% end %>
            </div>
          </div>
          <div class="card-footer text-muted text-center">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
              edited <%= time_ago_in_words(@article.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "btn btn-info btn-sm rounded-pill me-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, local: true) do |f| %>

  <div class="form-floating mb-4">
    <%= f.text_field :name, class: "form-control", placeholder: "Category name" %>
    <%= f.label :name, "Category name" %>
  </div>
  
  <div class="d-grid col-6 mx-auto mb-4">
    <%= f.submit class: "btn btn-primary btn-lg" %>
  </div>

<% end %>

app/views/categories/edit.html.erb
<main class="vh-100">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-6">
        <div class="card text-black rounded">
          <div class="card-body p-5">
            <h1 class="text-center fw-bold mb-4 mx-1 mx-md-4 mt-4">Edit category name</h1>
            <%= render 'form' %>
          </div>
        </div>
        <div class="row justify-content-center mt-3">
          <%= link_to "Cancel and return to category", category_path(@category), class: "link-light text-center" %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/categories/index.html.erb
<main>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 d-flex justify-content-center">
      <h1 class="col-lg-8 text-center text-white">Categories</h1>
    </div>
    <div class="flickr_pagination">
      <%= will_paginate @categories, :container => false %>
    </div>
    <div class="row gx-4 gx-lg-5 d-flex justify-content-center">
      <div class="col-lg-5">
        <% @categories.each do |category| %>
          <div class="card text-center mt-4">
            <div class="card-body">
              <h5 class="card-title"><%= link_to category.name, category_path(category) %></h5>
              <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
                edited <%= time_ago_in_words(category.updated_at) %> ago
              </small>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="flickr_pagination my-4">
      <%= will_paginate @categories, :container => false %>
    </div>
  </div>
</main>

app/views/categories/new.html.erb
<main class="vh-100">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-6">
        <div class="card text-black rounded">
          <div class="card-body p-5">
            <h1 class="text-center fw-bold mb-4 mx-1 mx-md-4 mt-4">Create a New Category</h1>
            <%= render 'form' %>
          </div>
        </div>
        <div class="row justify-content-center mt-3">
          <%= link_to "Cancel and return to categories listing", categories_path, class: "link-light text-center" %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/categories/show.html.erb
<main>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 d-flex justify-content-center">
      <h1 class="col-lg-8 text-center text-white">Category: <%= @category.name %></h1>
    </div>
    
    <% if logged_in? && current_user.admin? %>
      <div class="text-center mt-4">
        <%= link_to 'Edit category name', edit_category_path(@category), class: "btn btn-primary" %>
      </div>
    <% end %>
    
    <div class="flickr_pagination mt-4">
      <%= will_paginate @articles, :container => false %>
    </div>
    
    <%= render 'articles/articles' %>
    
    <div class="flickr_pagination my-4">
      <%= will_paginate @articles, :container => false %>
    </div>
    
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer class="mt-auto py-3 bg-dark">
  <div class="container px-3">
    <small class="d-flex justify-content-center text-muted text-white">
      Copyright &copy; 2022 - <%= link_to "NAKAMURA Yuka", "https://github.com/yukankmr/alpha_blog", class: "text-white" %>
    </small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container px-4 px-lg-5 mt-5 pt-4">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
          <%= msg %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-transparent fixed-top">
  <div class="container px-4 px-lg-5">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="dropdown-item">
              <%= link_to "View articles", articles_path, class: "nav-link text-dark" %>
            </li>
            <% if logged_in? %>
              <li class="dropdown-item">
                <%= link_to 'Create new article', new_article_path, class: "nav-link text-dark" %>
              </li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="dropdown-item">
              <%= link_to "View categories", categories_path, class: "nav-link text-dark" %>
            </li>
            <% if logged_in? && current_user.admin? %>
              <li class="dropdown-item">
                <%= link_to 'Create new category', new_category_path, class: "nav-link text-dark" %>
              </li>
            <% end %>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.username %>'s profile <%= "(Admin)" if current_user.admin? %> 
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="dropdown-item">
                <%= link_to "View your profile", user_path(current_user), class: "nav-link text-dark" %>
              </li>
              <li class="dropdown-item">
                <%= link_to 'Edit your profile', edit_user_path(current_user), class: "nav-link text-dark" %>
              </li>
              <li class="dropdown-item">
                <%= link_to 'Delete your profile', user_path(current_user), class: "nav-link text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to About page</h1>

app/views/pages/home.html.erb
<main id="page-height">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 text-center">
      <div class="col-lg-8 mx-auto">
        <h1 class="text-white font-weight-bold">Alpha Blog</h1>
      </div>
      <div class="col-lg-8 mx-auto">
        <p class="lead text-white mb-5">Share your stories, ideas and knowledge on any topic. Connect with writers worldwide.</p>
        <%= link_to "Sign up!", signup_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  </div>
</main>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<%= form_with(model: @user, local: true) do |f| %>

  <div class="form-floating mb-4">
    <%= f.text_field :username, class: "form-control", placeholder: "Your Name" %>
    <%= f.label :username %>
  </div>
  
  <div class="form-floating mb-4">
    <%= f.email_field :email, class: "form-control", placeholder: "Your Email" %>
    <%= f.label :email %>
  </div>
  
  <div class="form-floating mb-4">
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
    <%= f.label :password %>
  </div>
  
  <div class="d-grid col-6 mx-auto mb-4">
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg") %>
  </div>

<% end %>

app/views/users/edit.html.erb
<main class="vh-100">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-6">
        <div class="card text-black rounded">
          <div class="card-body p-5">
            <h1 class="text-center fw-bold mb-4 mx-1 mx-md-4 mt-4">Edit your profile</h1>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 d-flex justify-content-center">
      <h1 class="col-lg-8 text-center text-white">Alpha Bloggers</h1>
    </div>
    
    <div class="flickr_pagination">
      <%= will_paginate @users, :container => false %>
    </div>
    
    <div class="row gx-4 gx-lg-5 d-flex justify-content-center">
      <div class="col-lg-8">
        <% @users.each do |user| %>
          <div class="card text-center mt-4">
            <div class="card-header">
              <%= link_to user.username, user %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user %></h5>
              <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
                <%= link_to 'View profile', user, class: "btn btn-outline-info" %>
                <% if logged_in? %>
                  <% if user == current_user %>
                    <%= link_to 'Edit profile', edit_user_path(user.id), class: "btn btn-outline-primary" %>
                  <% end %>
                  <% if current_user.admin? %>
                    <%= link_to 'Delete user', user_path(user.id), class: "btn btn-outline-danger", method: :delete, 
                    data: {confirm: "Are you sure you want to delete the user account and all associated articles?"} %>
                  <% end %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>Joined <%= time_ago_in_words(user.created_at) %></small>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="flickr_pagination my-4">
      <%= will_paginate @users, :container => false %>
    </div>
    
  </div>
</main>

app/views/users/new.html.erb
<main class="vh-100">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-6">
        <div class="card text-black rounded">
          <div class="card-body p-5">
            <h1 class="text-center fw-bold mb-4 mx-1 mx-md-4 mt-4">Sign up</h1>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 d-flex justify-content-center">
      <h1 class="col-lg-8 text-center text-white"><%= @user.username %>'s profile</h1>
    </div>
    <%= gravatar_for @user, size: 200 %>
    
    <% if logged_in? && @user == current_user %>
      <div class="text-center mt-4">
        <%= link_to 'Edit your profile', edit_user_path(@user), class: "btn btn-primary" %>
      </div>
    <% end %>
    
    <div class="flickr_pagination mt-4">
      <%= will_paginate @articles, :container => false %>
    </div>
    
    <%= render 'articles/articles' %>
    
    <div class="flickr_pagination my-4">
      <%= will_paginate @articles, :container => false %>
    </div>
    
  </div>
</main>